- platform: mqtt
  name: technical_valve1
  state_topic: "command/technical/waterflow"
  command_topic: "command/technical/waterflow"
  payload_on: "1" #open valve 1
  payload_off: "2" #close valve 1
  retain: false
  
- platform: mqtt
  name: technical_valve2
  state_topic: "command/technical/waterflow"
  command_topic: "command/technical/waterflow"
  payload_on: "3" #open valve 2
  payload_off: "4" #close valve 2
  retain: false
  
- platform: mqtt
  name: pool_filter
  state_topic: "command/pool/filter"
  command_topic: "command/pool/filter"
  payload_on: "1" 
  payload_off: "0" 
  retain: false
  
- platform: mqtt
  name: pool_light
  state_topic: "command/pool/light"
  command_topic: "command/pool/light"
  payload_on: "1" 
  payload_off: "0" 
  retain: false

- platform: mqtt
  name: pool_ph
  state_topic: "command/pool/ph"
  command_topic: "command/pool/ph"
  payload_on: "1" 
  payload_off: "0" 
  retain: false