
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

sun:

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
input_number: !include_dir_merge_named input_numbers
binary_sensor: !include_dir_merge_list binary_sensors

influxdb: !include influxdb.yaml

recorder: !include recorder.yaml

frontend:
  themes: !include_dir_merge_named themes
  
# media_player: !include_dir_merge_list media
modbus: !include komfovent.yaml
mqtt: !include mqtt.yaml

homeassistant:
  allowlist_external_dirs:
    - "/config/www/tmp"
  media_dirs:
    local: "/config/www/tmp_doorbell"

    
camera:   
  - platform: local_file
    file_path: /config/www/tmp_doorbell/doorbell_visitor.jpg
    name: Doorbell Visitor

  - platform: local_file
    file_path: /config/www/tmp_doorbell/doorbell_person.jpg
    name: Doorbell Person

  - platform: local_file
    file_path: /config/www/tmp_doorbell/doorbell_motion.jpg
    name: Doorbell Motion

telegram_bot:
  - platform: broadcast
    api_key:  !secret telegram_key
    allowed_chat_ids:
      - 1863022133 # example id of a user

