- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/all"
  name: "Blind all"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/calibration"
  name: "Blind calibration"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/living-pos"
  name: "Blind living position"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/kitchen-pos"
  name: "Blind kitchen position"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/terrace-pos"
  name: "Blind terrace position"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/bed-pos"
  name: "Blind bed position"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/office-pos"
  name: "Blind office position"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/child1-pos"
  name: "Blind child1 position"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/child2-pos"
  name: "Blind child2 position"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/child3-pos"
  name: "Blind child3 position"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/living-tilt"
  name: "Blind living tilt"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/kitchen-tilt"
  name: "Blind kitchen tilt"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/terrace-tilt"
  name: "Blind terrace tilt"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/bed-tilt"
  name: "Blind bed tilt"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/office-tilt"
  name: "Blind office tilt"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/child1-tilt"
  name: "Blind child1 tilt"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/child2-tilt"
  name: "Blind child2 tilt"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/child3-tilt"
  name: "Blind child3 tilt"

- platform: mqtt
  force_update: true
  state_topic: "sensor/blind/mode"
  name: "Blind mode"

