#SQLITE
# MAIN
- platform: sql
  queries:
    - name: l1 daily con
      query: >
        SELECT round(sum(state/100),2) as state FROM states WHERE entity_id = "sensor.foyer_l1_consumption_increment" and date(last_updated) = date("now");
      column: 'state'
      unit_of_measurement: "kWh"

- platform: sql
  queries:
    - name: l2 daily con
      query: >
        SELECT round(sum(state/100),2) as state FROM states WHERE entity_id = "sensor.foyer_l2_consumption_increment" and date(last_updated) = date("now");
      column: 'state'
      unit_of_measurement: "kWh"

- platform: sql
  queries:
    - name: l3 daily con
      query: >
        SELECT round(sum(state/100),2) as state FROM states WHERE entity_id = "sensor.foyer_l3_consumption_increment" and date(last_updated) = date("now");
      column: 'state'
      unit_of_measurement: "kWh"

# APPLIANCES
- platform: sql
  queries:
    - name: l1 oven sum
      query: >
        SELECT round(sum(state/100),2) as state FROM states WHERE entity_id = "sensor.foyer_l1_oven_increment" and date(last_updated) = date("now");
      column: 'state'
      unit_of_measurement: "kWh"

- platform: sql
  queries:
    - name: l2 refrigerator sum
      query: >
        SELECT round(sum(state/100),2) as state FROM states WHERE entity_id = "sensor.foyer_l2_refrigerator_increment" and date(last_updated) = date("now");
      column: 'state'
      unit_of_measurement: "kWh"

- platform: sql
  queries:
    - name: l3 dishwasher sum
      query: >
        SELECT round(sum(state/100),2) as state FROM states WHERE entity_id = "sensor.foyer_l3_dishwasher_increment" and date(last_updated) = date("now");
      column: 'state'
      unit_of_measurement: "kWh"

- platform: sql
  queries:
    - name: sum daily con
      query: >
        SELECT round(sum(state/100),2) as state FROM states WHERE entity_id in("sensor.foyer_l1_consumption_increment", "sensor.foyer_l2_consumption_increment", "sensor.foyer_l3_consumption_increment") and date(last_updated) = date("now");
      column: 'state'
      unit_of_measurement: "kWh"
