- platform: mqtt
  force_update: true
  state_topic: "sensor/foyer/L1_power"
  name: "Foyer L1 power"
  unit_of_measurement: "W"

- platform: mqtt
  force_update: true
  state_topic: "sensor/foyer/L2_power"
  name: "Foyer L2 power"
  unit_of_measurement: "W"

- platform: mqtt
  force_update: true
  state_topic: "sensor/foyer/L3_power"
  name: "Foyer L3 power"
  unit_of_measurement: "W"

- platform: mqtt
  force_update: true
  state_topic: "sensor/foyer/L1_consum"
  name: "Foyer L1 consumption"
  unit_of_measurement: "kWh"

- platform: mqtt
  force_update: true
  state_topic: "sensor/foyer/L2_consum"
  name: "Foyer L2 consumption"
  unit_of_measurement: "kWh"

- platform: mqtt
  force_update: true
  state_topic: "sensor/foyer/L3_consum"
  name: "Foyer L3 consumption"
  unit_of_measurement: "kWh"

- platform: mqtt
  force_update: true 
  state_topic: "sensor/foyer/L1_con_inc"
  name: "Foyer L1 consumption increment"
  unit_of_measurement: "kWh"

- platform: mqtt
  force_update: true 
  state_topic: "sensor/foyer/L2_con_inc"
  name: "Foyer L2 consumption increment"
  unit_of_measurement: "kWh"

- platform: mqtt
  force_update: true 
  state_topic: "sensor/foyer/L3_con_inc"
  name: "Foyer L3 consumption increment"
  unit_of_measurement: "kWh"

- platform: mqtt
  state_topic: "sensor/foyer/connection_failed"
  name: "Foyer connection failed"


#SQLITE

- platform: sql
  scan_interval: 3600
  queries:
    - name: l1 daily con
      query: >
        SELECT round(sum(state/100),2) as state FROM states WHERE entity_id = "sensor.foyer_l1_consumption_increment" and date(last_updated) = date("now");
      column: 'state'
      unit_of_measurement: "kWh"

- platform: sql
  scan_interval: 3600
  queries:
    - name: l2 daily con
      query: >
        SELECT round(sum(state/100),2) as state FROM states WHERE entity_id = "sensor.foyer_l2_consumption_increment" and date(last_updated) = date("now");
      column: 'state'
      unit_of_measurement: "kWh"

- platform: sql
  scan_interval: 3600
  queries:
    - name: l3 daily con
      query: >
        SELECT round(sum(state/100),2) as state FROM states WHERE entity_id = "sensor.foyer_l3_consumption_increment" and date(last_updated) = date("now");
      column: 'state'
      unit_of_measurement: "kWh"
