- platform: template
  sensors:
    time_of_day:
      friendly_name: "Time of Day"
      value_template: >-
        {% if is_state('binary_sensor.morning', 'on') %}
          Morning
        {% elif is_state('binary_sensor.afternoon', 'on') %}
          Afternoon
        {% elif is_state('binary_sensor.evening', 'on') %}
          Evening
        {% else %}
          Night
        {% endif %}

    dishwasher_status:
      friendly_name: "Dishwasher Status"
      value_template: >-
        {% if states("sensor.foyer_l3_dishwasher_power")|float <= 2 %}
          Off
        {% else %}
          On
        {% endif %}
      icon_template: >-
        {% if states("sensor.foyer_l3_dishwasher_power")|float <= 2 %}
          mdi:dishwasher-off
        {% else %}
          mdi:dishwasher
        {% endif %}