# SQLITE
- platform: sql
  scan_interval: 3600
  queries:
    - name: internal water daily
      query: >
        SELECT round(sum(state),2) as state FROM states WHERE entity_id = "sensor.technical_inter_liters" and date(last_updated) = date("now");
      column: "state"
      unit_of_measurement: "l"

- platform: sql
  scan_interval: 3600
  queries:
    - name: external water daily
      query: >
        SELECT round(sum(state),2) as state FROM states WHERE entity_id = "sensor.technical_exter_liters" and date(last_updated) = date("now");
      column: "state"
      unit_of_measurement: "l"
