- platform: tod
  name: Morning
  after: sunrise
  after_offset: "-01:00"
  before: "12:00"

- platform: tod
  name: Afternoon
  after: "12:00"
  before: "17:00"

- platform: tod
  name: Evening
  after: "17:00"
  before: "22:00"

- platform: tod
  name: Night
  after: "22:00"
  before: sunrise
