esphome:
  name: eps32-test
  friendly_name: eps32_test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "VcSe+uw/hvDZDa0vUXRIQQMagHidTTTduJhxq0opWVs="

ota:
  password: "824945c5f48a2ed382f03a378feac842"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Eps32-Test Fallback Hotspot"
    password: "RJTmoVx9RYBn"

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

mcp23017:
  - id: 'mcp23017_1'
    address: 0x20

switch:
  - platform: gpio
    name: "MCP23017 Pin A0"
    id: mcp_A0
    pin:
      mcp23xxx: mcp23017_1
      # Use pin A0
      number: 0
      mode:
        output: true
      inverted: false
    interlock: [mcp_B0]
    interlock_wait_time: 800ms

  - platform: gpio
    name: "MCP23017 Pin B0"
    id: mcp_B0
    pin:
      mcp23xxx: mcp23017_1
      # Use pin B0
      number: 8
      mode:
        output: true
      inverted: false
    interlock: [mcp_A0]
    interlock_wait_time: 800ms

  - platform: gpio
    name: "MCP23017 Pin A1"
    id: mcp_A1
    pin:
      mcp23xxx: mcp23017_1
      # Use pin A1
      number: 1
      mode:
        output: true
      inverted: false
    interlock: [mcp_B1]
    interlock_wait_time: 800ms

  - platform: gpio
    name: "MCP23017 Pin B1"
    id: mcp_B1
    pin:
      mcp23xxx: mcp23017_1
      # Use pin B1
      number: 9
      mode:
        output: true
      inverted: false
    interlock: [mcp_A1]
    interlock_wait_time: 800ms

  - platform: gpio
    name: "MCP23017 Pin A2"
    id: mcp_A2
    pin:
      mcp23xxx: mcp23017_1
      # Use pin A2
      number: 2
      mode:
        output: true
      inverted: false
    interlock: [mcp_B2]
    interlock_wait_time: 800ms

  - platform: gpio
    name: "MCP23017 Pin B2"
    id: mcp_B2
    pin:
      mcp23xxx: mcp23017_1
      # Use pin B2
      number: 10
      mode:
        output: true
      inverted: false
    interlock: [mcp_A2]
    interlock_wait_time: 800ms

  - platform: gpio
    name: "MCP23017 Pin A3"
    id: mcp_A3
    pin:
      mcp23xxx: mcp23017_1
      # Use pin A3
      number: 3
      mode:
        output: true
      inverted: false
    interlock: [mcp_B3]
    interlock_wait_time: 800ms

  - platform: gpio
    name: "MCP23017 Pin B3"
    id: mcp_B3
    pin:
      mcp23xxx: mcp23017_1
      # Use pin B3
      number: 11
      mode:
        output: true
      inverted: false
    interlock: [mcp_A3]
    interlock_wait_time: 800ms

  - platform: gpio
    name: "MCP23017 Pin A4"
    id: mcp_A4
    pin:
      mcp23xxx: mcp23017_1
      # Use pin A4
      number: 4
      mode:
        output: true
      inverted: false
    interlock: [mcp_B4]
    interlock_wait_time: 800ms

  - platform: gpio
    name: "MCP23017 Pin B4"
    id: mcp_B4
    pin:
      mcp23xxx: mcp23017_1
      # Use pin B4
      number: 12
      mode:
        output: true
      inverted: false
    interlock: [mcp_A4]
    interlock_wait_time: 800ms
